# Generated by Django 6.0.2 on 2026-02-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='data_preview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
